/* Traductions propres à mandat2.html.
   11 clés. Enregistré par js/i18n.js. */

i18nAjouter({
  fr: {
    "mandat2-img-alt": "Analyse exploratoire RH, Business Intelligence",
    "mandat2-eyebrow": "Mandat · Analyse RH & BI",
    "mandat2-title": "Analyse exploratoire RH et modélisation des effectifs",
    "mandat2-meta1": "Données RH · Business Intelligence",
    "mandat2-meta2": "Nettoyage, structuration, indicateurs fiables, confidentialité",
    "mandat2-h2-1": "CONTEXTE",
    "mandat2-p1": "Ce travail s’inscrit dans le cadre d’une analyse exploratoire visant à démontrer la valeur qu’une solution de Business Intelligence peut apporter en utilisant des données RH extraites d’un système existant. Les données fournies représentent un échantillon de l’effectif de l’entreprise et incluent des informations relatives aux employés, aux départements et aux unités d’affaires.<br>L’objectif est d’analyser la structure réelle et la qualité des données, d’identifier ce qui est fiable d’un point de vue analytique et de produire des indicateurs concrets et exploitables, tout en respectant strictement les contraintes de confidentialité des données.",
    "mandat2-h2-2": "IMPORTATION ET NETTOYAGE DES DONNÉES",
    "mandat2-p2": "La première étape a consisté à nettoyer et à préparer les données afin d’en garantir la cohérence et la fiabilité pour l’analyse. Les types de données ont été standardisés, notamment pour les identifiants, les dates et les montants financiers, et des vérifications ont été effectuées pour repérer les lignes vides et les doublons exacts.<br>Les intitulés de poste ont été nettoyés et les incohérences typographiques ont été corrigées (par exemple, « Sr. Manger » a été remplacé par « Sr. Manager »). Les noms de colonnes techniques ont été renommés pour améliorer la lisibilité du modèle, et les informations sensibles telles que les noms complets des employés ont été supprimées conformément aux bonnes pratiques en matière de confidentialité des données.<br>Lors de l’analyse exploratoire, une attention particulière a été portée à la compréhension de la granularité des données. Il a été observé que différents employés peuvent partager le même EEID, ce qui signifie que l’EEID ne représente pas un identifiant unique d’employé, mais plutôt un identifiant au niveau de l’enregistrement.<br>Afin de déterminer précisément le nombre d’employés, une validation croisée des noms, de l’âge, du sexe et des dates d’embauche a été réalisée. Cette analyse a révélé des cas où des employés portant des noms identiques présentaient des caractéristiques démographiques et temporelles incompatibles avec l’hypothèse qu’il s’agissait de la même personne. Par exemple, des employés ayant le même nom pouvaient avoir des âges significativement différents et des années d’embauche très éloignées, ce qui exclut des scénarios tels que des réembauches ou des changements de poste internes.<br>Sur la base de ces observations, il a été conclu que, dans le cadre de ce jeu de données, chaque ligne représente un employé distinct. Cette conclusion repose sur des observations factuelles des données et est explicitement énoncée comme une hypothèse de travail pour le reste de l’analyse.",
    "mandat2-h2-3": "MODÉLISATION DES DONNÉES",
    "mandat2-p3": "Sur la base de cette compréhension, plusieurs colonnes calculées ont été créées afin d’enrichir le jeu de données sans introduire d’hypothèses risquées. Une colonne Statut a été ajoutée pour identifier si un employé est actif ou inactif, en fonction de la présence d’une date de départ. Une colonne Ancienneté (Années) a également été calculée pour mesurer la durée d’emploi, permettant ainsi d’analyser l’expérience globale de l’effectif.<br>De plus, une table Date dédiée a été créée pour soutenir l’analyse temporelle. Des relations ont ensuite été établies de manière simple et cohérente, liant la table principale des employés aux tables des départements, des unités d’affaires et des dates par le biais de leurs identifiants respectifs.<br>Ce modèle relationnel permet une navigation fluide entre les analyses et garantit que les indicateurs calculés peuvent être analysés de manière cohérente par département, unité d’affaires, pays ou toute autre dimension organisationnelle pertinente.<br>Du point de vue des calculs, seuls les indicateurs jugés fiables compte tenu des données disponibles ont été retenus. L’effectif total est calculé comme le nombre de lignes du jeu de données, conformément à l’hypothèse validée selon laquelle chaque ligne correspond à un employé distinct dans cet échantillon.<br>Des indicateurs agrégés tels que le salaire moyen, le pourcentage de prime moyen et l’ancienneté moyenne ont été calculés afin de fournir un aperçu concis et pertinent de la structure de rémunération de l’entreprise et de l’expérience de son effectif."
  },
  en: {
    "mandat2-img-alt": "HR exploratory analysis, Business Intelligence",
    "mandat2-eyebrow": "Mandate · HR & BI Analysis",
    "mandat2-title": "HR exploratory analysis and workforce modeling",
    "mandat2-meta1": "HR data · Business Intelligence",
    "mandat2-meta2": "Cleaning, structuring, reliable indicators, confidentiality",
    "mandat2-h2-1": "CONTEXT",
    "mandat2-p1": "This work is part of an exploratory analysis aimed at demonstrating the value a Business Intelligence solution can bring by leveraging HR data extracted from an existing system. The data provided represents a sample of the company’s workforce and includes information related to employees, departments and business units.<br>The goal is to analyze the actual structure and quality of the data, identify what is analytically reliable, and produce concrete and actionable indicators, while strictly respecting data confidentiality constraints.",
    "mandat2-h2-2": "DATA IMPORT AND CLEANING",
    "mandat2-p2": "The first step was to clean and prepare the data to ensure its consistency and reliability for analysis. Data types were standardized, particularly for IDs, dates and financial amounts, and checks were performed to identify empty rows and exact duplicates.<br>Job titles were cleaned and typographical inconsistencies corrected (for example, “Sr. Manger” was replaced by “Sr. Manager”). Technical column names were renamed to improve model readability, and sensitive information such as employee full names was removed in line with data privacy best practices.<br>During exploratory analysis, particular attention was paid to understanding data granularity. It was observed that different employees can share the same EEID, meaning the EEID does not represent a unique employee identifier, but rather a record-level identifier.<br>To accurately determine the number of employees, a cross-validation of names, age, gender and hire dates was carried out. This analysis revealed cases where employees with identical names had demographic and temporal characteristics incompatible with the assumption they were the same person. For example, employees sharing the same name could have significantly different ages and very distant hire years, which rules out scenarios such as rehires or internal role changes.<br>Based on these observations, it was concluded that, within the scope of this dataset, each row represents a distinct employee. This conclusion is supported by factual observations of the data and is explicitly stated as a working hypothesis for the rest of the analysis.",
    "mandat2-h2-3": "DATA MODELING",
    "mandat2-p3": "Building on this understanding, several calculated columns were created to enrich the dataset without introducing risky assumptions. A Status column was added to identify whether an employee is active or inactive, based on the presence of an exit date. A Tenure (Years) column was also calculated to measure length of employment, enabling analysis of overall workforce experience.<br>In addition, a dedicated Date table was created to support time-based analysis. Relationships were then established in a simple and consistent way, linking the main employee table to the department, business unit and date tables through their respective identifiers.<br>This relational model enables smooth navigation between analyses and ensures that calculated indicators can be analyzed consistently by department, business unit, country or any other relevant organizational dimension.<br>From a calculation standpoint, only indicators considered reliable given the available data were retained. Total headcount is calculated as the number of rows in the dataset, in line with the validated assumption that each row corresponds to a distinct employee in this sample.<br>Aggregated indicators such as average salary, average bonus percentage and average tenure were calculated to provide a concise and meaningful overview of the company’s compensation structure and workforce experience."
  }
});
